language: php

cache:
    directories:
      - "$HOME/.composer/cache"

matrix:
  fast_finish: true
  include:
    - php: '5.6'
    - php: '7.0'
    - php: '7.1'
    - php: '7.2'
    - php: '7.2'
      env: COVERAGE=yes
    - php: '7.3'
  allow_failures:
    - php: '7.2'
      env: COVERAGE=yes
    - php: '7.3'

before_install:
  - if [[ $COVERAGE != yes ]]; then phpenv config-rm xdebug.ini; fi;
  - pecl channel-update pecl.php.net
  - phpenv config-add ./etc/travis/phpenv.ini

install:
  - travis_retry composer install --no-interaction

script:
  - 'if [[ ${COVERAGE}=yes ]]; then
        ./vendor/bin/phpunit --verbose --coverage-clover=clover.xml --coverage-php=clover.serialized;
    else
        ./vendor/bin/phpunit --verbose;
    fi'

after_script:
  - 'if [[ $COVERAGE = yes ]]; then
        composer require --no-scripts php-coveralls/php-coveralls;
        travis_retry ./vendor/bin/php-coveralls -vvv;
        wget https://scrutinizer-ci.com/ocular.phar;
        travis_retry php ocular.phar code-coverage:upload --format=php-clover clover.xml;
    fi'