language: php

cache:
    directories:
      - "$HOME/.composer/cache"

matrix:
  fast_finish: true
  include:
    - php: '7.4'
    - php: '7.4'
      env: COVERAGE=yes
  allow_failures:
    - php: '7.4'
      env: COVERAGE=yes

before_install:
  - if [[ $COVERAGE != yes ]]; then phpenv config-rm xdebug.ini || echo "xdebug not available"; fi
  - pecl channel-update pecl.php.net
  - phpenv config-add ./etc/travis/phpenv.ini
  - travis_retry composer self-update --2

install:
  - pecl channel-update pecl.php.net
  - php --ri mongodb || pecl install -f mongodb
  - travis_retry composer install --no-interaction

script:
  - 'if [[ $COVERAGE=yes ]]; then
        ./vendor/bin/phpunit --verbose --coverage-clover clover.xml;
    else
        ./vendor/bin/phpunit --verbose;
    fi'

after_script:
  - 'if [[ $COVERAGE = yes ]]; then
        composer require --no-scripts php-coveralls/php-coveralls;
        travis_retry ./vendor/bin/php-coveralls -vvv;
        wget https://scrutinizer-ci.com/ocular.phar;
        travis_retry php ocular.phar code-coverage:upload --format=php-clover clover.xml;
    fi'